- name: PUSH AS3
  uri:
     url: "https://{{ ansible_host }}:8443/mgmt/shared/appsvcs/declare"
     method: POST
     body: "{{ lookup('template','j2/tenant_base.j2', split_lines=False) }}"
     status_code: 200
     timeout: 300
     body_format: json
     force_basic_auth: yes
     user: "{{ ansible_user }}"
     password: "{{ ansible_ssh_pass }}"
     validate_certs: no
  delegate_to: localhost