- name: Remove VS, WIP and components
  hosts: F5VM
  connection: local

#pass in credentials from tower
  vars:
    provider:
      user: "{{ username }}"
      password: "{{ password }}"
      server: 192.168.1.100
      validate_certs: no


  tasks:
      - name: Remove a GTM WIP
        bigip_gtm_wide_ip:
          provider: "{{ provider }}"
          name: testwip.scottslab
          state: absent
          pool_lb_method: round-robin
          type: a
          pools: 
          -  name: vip-1_pool

      - name: Remove a GTM pool
        bigip_gtm_pool:
          provider: "{{ provider }}"
          name: vip-1_pool
          state: absent
          preferred_lb_method: round-robin
          type: a

      - name: Remove a GTM VS
        bigip_gtm_virtual_server:
          provider: "{{ provider }}"
          name: vip-1
          state: absent
          address: 172.16.10.108
          server_name: bigip1
          port: 80
          

      - name: Remove a VS
        bigip_virtual_server:
          provider: "{{ provider }}"
          name: vip-1
          state: absent
          description: VS made by ansible tower
          destination: 172.16.10.108
          pool: web
          port: 80
          snat: Automap
          profiles:
            - http

      - name: Remove a pool
        bigip_pool:
          provider: "{{ provider }}"
          name: web
          state: absent
          lb_method: ratio-member
          slow_ramp_time: 120