- name: Create a VIP, pool and pool members then GTM VS, Pool and WIP
  hosts: F5VM
  connection: local

#pass in credentials from tower
  vars:
    provider:
      user: "{{ username }}"
      password: "{{ password }}"
      server: 192.168.1.100
      validate_certs: no

  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: round-robin
        name: Pool_"{{ appname }}"
        slow_ramp_time: 120

    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: Pool_"{{ appname }}"
        port: "{{ serverport }}"
      with_items:
        - host: 10.10.10.10
          name: web01
        - host: 10.10.10.20
          name: web02

    - name: Create a HTTP VS
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: VS made by ansible tower
        destination: "{{ listenerIP }}"
        name: VS_"{{ appname }}"
        pool: Pool_"{{ appname }}"
        port: "{{ listenerport}}"
        snat: Automap

    - name: Create a GTM VS
      bigip_gtm_virtual_server:
        provider: "{{ provider }}"
        address: "{{ listenerIP }}"
        name: VS_"{{ appname }}"
        server_name: bigip1
        port: "{{ listenerport}}"
        
    - name: Create a GTM pool
      bigip_gtm_pool:
        provider: "{{ provider }}"
        name: GTMPool_"{{ appname }}"
        preferred_lb_method: round-robin
        type: a

    - name: Add members to GTM pool
      bigip_gtm_pool_member:
        pool: GTMPool_"{{ appname }}"
        server_name: bigip1
        virtual_server: VS_"{{ appname }}"
        type: a
        provider: "{{ provider }}"

    - name: Create a GTM WIP
      bigip_gtm_wide_ip:
        provider: "{{ provider }}"
        name: "{{ appname }}".scottlab
        pool_lb_method: round-robin
        type: a
        pools: 
        -  name: GTMPool_"{{ appname }}"