- name: Create a VIP, pool and pool members
  hosts: F5VM
  connection: local

#pretty sure you can pass in tower creds but for now since its a lab stick to this
  vars:
    provider:
      user: admin
      password: admin
      server: 192.168.1.100
      validate_certs: no

  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120

    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: web
        port: 80
      with_items:
        - host: 10.10.10.10
          name: web01
        - host: 10.10.10.20
          name: web02

    - name: Create a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: VS made by ansible tower
        destination: 172.16.10.108
        name: vip-1
        pool: web
        port: 80
        snat: Automap
        profiles:
          - http

    - name: Create a GTM VS
      bigip_gtm_virtual_server:
        provider: "{{ provider }}"
        address: 172.16.10.108
        name: vip-1
        server_name: bigip1
        port: 80
        
    - name: Create a GTM pool
      bigip_gtm_pool:
        provider: "{{ provider }}"
        name: vip-1_pool
        preferred_lb_method: round robin
        type: a

    - name: Add members to GTM pool
      bigip_gtm_pool_member:
        pool: vip-1_pool
        server_name: bigip1
        virtual_server: vip-1
        type: a
        provider: "{{ provider }}"

    - name: Create a GTM WIP
      bigip_gtm_wide_ip:
        provider: "{{ provider }}"
        name: testwip.scottslab
        pool_lb_method: round robin
        pool: vip-1_pool