- name: Remove VS, WIP and components
  hosts: F5VM
  connection: local

#pass in credentials from tower
  vars:
    provider:
      user: "{{ username }}"
      password: "{{ password }}"
      server: 192.168.1.100
      validate_certs: no


  tasks:
      - name: Remove a GTM WIP
        bigip_gtm_wide_ip:
        provider: "{{ provider }}"
        name: testwip.scottslab
        state: absent

    - name: Remove a GTM pool
      bigip_gtm_pool:
        provider: "{{ provider }}"
        name: vip-1_pool
        state: absent

    - name: Remove a GTM VS
      bigip_gtm_virtual_server:
        provider: "{{ provider }}"
        name: vip-1
        state: absent  

    - name: Remove a VS
      bigip_virtual_server:
        provider: "{{ provider }}"
        name: vip-1
        state: absent

    - name: Remove a pool
      bigip_pool:
        provider: "{{ provider }}"
        name: web
        state: absent



